Repository SimonThormeyer/beuthSoundGroup, pull requests merged in 2020-05, with the labels that each got.

#22 closes #12
  Frontend/.gitignore
  Frontend/README.md
  Frontend/package.json
  Frontend/platz_halter.js
  Frontend/public/favicon.ico
  Frontend/public/index.html
  Frontend/public/logo192.png
  Frontend/public/logo512.png
  Frontend/public/manifest.json
  Frontend/public/robots.txt
  Frontend/src/components/menu.js
  Frontend/src/components/threeJS/canvas.js
  Frontend/src/components/toneJS/synth.js
  Frontend/src/containers/App.js
  Frontend/src/index.css
  Frontend/src/index.js
  Frontend/src/logo.svg
  Frontend/src/serviceWorker.js
  Frontend/yarn.lock
Labels: frontend

#52 menue
  Frontend/src/components/menu.js
  Frontend/src/containers/App.js
  Frontend/src/img/looper.svg
  Frontend/src/img/pause.svg
  Frontend/src/img/play.svg
  Frontend/src/img/random.svg
  Frontend/src/img/record.svg
  Frontend/src/img/stop.svg
  Frontend/src/index.css
Labels: frontend

#53 fix sound problem (again)
  Frontend/src/containers/App.js
Labels: bug

#59 adding docker files for frontend and integrating frontend and backend
  Backend/api/app.py
  Docker-Cheatsheet.md
  Frontend/Dockerfile
  Frontend/docker-compose.yaml
  Frontend/entrypoint.sh
  docker-compose.yaml
Labels: backend, docker, frontend

#65 patch_tickets_to_engl
  .github/ISSUE_TEMPLATE/ticket.md
Labels: pull request

#67 Create bug.md
  .github/ISSUE_TEMPLATE/bug.md
Labels: pull request

#66 Update user-story.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: pull request

#68 Create bug_fix_pull_request.md
  .github/ISSUE_TEMPLATE/bug_fix.md
Labels: pull request

#64 Ticket/58/code cleanup simon
  Frontend/package.json
  Frontend/src/GlobalState.js
  Frontend/src/components/menu.js
  Frontend/src/components/toneJS/Looper.js
  Frontend/src/containers/App.js
  Frontend/src/containers/Parent.js
  Frontend/yarn.lock
Labels: pull request

#96 loopicon with animation and interactive controls
  Frontend/public/favicon.ico
  Frontend/public/favicon.svg
  Frontend/public/index.html
  Frontend/src/components/loopicon.js
  Frontend/src/containers/App.js
  Frontend/src/containers/loopcontrols.js
  Frontend/src/img/delete.svg
  Frontend/src/img/mute.svg
  Frontend/src/img/pause.svg
  Frontend/src/img/play.svg
  Frontend/src/img/volume.svg
  Frontend/src/index.css
Labels: Buttons / Menu, pull request
